from main.views.main import MainView
from main.views.detail import NewDetailView
from main.views.create import CreateNewView
from main.views.delete import DeleteNewView
from main.views.update import UpdateNewView
from main.views.create_user import CreateUserView
from main.views.delete_coment import DeleteComentView
from main.views.users import UsersView
from main.views.email_confirm import EmailConfirmView
from main.views.login import CustomLoginView
from main.views.logout import CustomLogoutView
